### ISSUE TITLE
breaking application changes / @imtbl/sdk - reference failure 

### ISSUE THREAD

**Issue by traemoore** [immutable/immutable-zkevm-example-marketplace#2]
I pulled the project down to start understanding the platform integration and sdk's. In getting the project to work, I had to update packages and references. I have created a branch with the fixes and highlighted an internal error in @imtbl/sdk. 

In the image below, I had to add the file extension to get the project to run. I love what IMX is doing and would love the opportunity to contribute... 
![image](https://github.com/immutable/immutable-zkevm-example-marketplace/assets/108375644/ce519d91-f284-4297-80bf-d785d059da9e)

**Comment by frankisawesome** [comment]
Hey @traemoore appreciate you raising this, we currently don't have the capacity to allow and review public pull requests for this repo but I have fixed the problem on main :)
